"""add mizaj and consultation preference fields

Revision ID: 3258c0e1a671
Revises: 90cded402778
Create Date: 2026-07-30 13:39:40.581614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3258c0e1a671'
down_revision: Union[str, Sequence[str], None] = '90cded402778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mizaj_type', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('mizaj_assessment_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('preferred_hakeem_gender', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_hakeem_gender')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'mizaj_assessment_answers')
    op.drop_column('users', 'mizaj_type')
    # ### end Alembic commands ###
