"""add community posts, likes, comments, follows

Revision ID: c583e34e1dad
Revises: 3258c0e1a671
Create Date: 2026-08-01 16:25:14.157830

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c583e34e1dad'
down_revision: Union[str, Sequence[str], None] = '3258c0e1a671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POST_CATEGORIES = [
    ("ancestral_wisdom", "Ancestral Wisdom"),
    ("herbal_tea", "Herbal Tea"),
    ("skin_health", "Skin Health"),
    ("digestion", "Digestion"),
    ("mindfulness", "Mindfulness"),
    ("seasons", "Seasons"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follows_follower_followed')
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['lookup_options.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_category_id'), 'posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_author_id'), 'post_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_comments_created_at'), 'post_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_likes_post_user')
    )
    # ### end Alembic commands ###

    lookup_table = sa.table(
        'lookup_options',
        sa.column('id', sa.UUID()),
        sa.column('type', sa.String()),
        sa.column('key', sa.String()),
        sa.column('label', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('icon', sa.String()),
        sa.column('sort_order', sa.Integer()),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(
        lookup_table,
        [
            {
                'id': uuid.uuid4(),
                'type': 'post_category',
                'key': key,
                'label': label,
                'description': None,
                'icon': None,
                'sort_order': idx,
                'is_active': True,
            }
            for idx, (key, label) in enumerate(POST_CATEGORIES)
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM lookup_options WHERE type = 'post_category'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_created_at'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_author_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_category_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('follows')
    # ### end Alembic commands ###
